#ifndef _HD44780
#define _HD44780

#include "Myfun.h"

#define LCD_RS_GPIO			GPIOF
#define LCD_RS_MODER_R	GPIO_MODER_MODER2
#define LCD_RS_MODER		GPIO_MODER_MODER2_0
#define LCD_RS_PUPDR		GPIO_PUPDR_PUPDR2_0
#define LCD_RS_HIGH			GPIOF->ODR |= GPIO_ODR_OD2
#define LCD_RS_LOW			GPIOF->ODR &= ~GPIO_ODR_OD2

#define LCD_RW_GPIO			GPIOD
#define LCD_RW_MODER_R	GPIO_MODER_MODER4
#define LCD_RW_MODER		GPIO_MODER_MODER4_0
#define LCD_RW_PUPDR		GPIO_PUPDR_PUPDR4_0
#define LCD_RW_HIGH			GPIOD->ODR |= GPIO_ODR_OD4
#define LCD_RW_LOW			GPIOD->ODR &= ~GPIO_ODR_OD4

#define LCD_E_GPIO			GPIOD
#define LCD_E_MODER_R		GPIO_MODER_MODER5
#define LCD_E_MODER			GPIO_MODER_MODER5_0
#define LCD_E_PUPDR			GPIO_PUPDR_PUPDR5_0
#define LCD_E_HIGH			GPIOD->ODR |= GPIO_ODR_OD5
#define LCD_E_LOW				GPIOD->ODR &= ~GPIO_ODR_OD5

#define LCD_DB4_GPIO		GPIOE
#define LCD_DB4_MODER_R	GPIO_MODER_MODER7
#define LCD_DB4_MODER		GPIO_MODER_MODER7_0
#define LCD_DB4_PUPDR		GPIO_PUPDR_PUPDR7_0
#define LCD_DB4_HIGH		GPIOE->ODR |= GPIO_ODR_OD7
#define LCD_DB4_LOW			GPIOE->ODR &= ~GPIO_ODR_OD7

#define LCD_DB5_GPIO		GPIOE
#define LCD_DB5_MODER_R	GPIO_MODER_MODER8
#define LCD_DB5_MODER		GPIO_MODER_MODER8_0
#define LCD_DB5_PUPDR		GPIO_PUPDR_PUPDR8_0
#define LCD_DB5_HIGH		GPIOE->ODR |= GPIO_ODR_OD8
#define LCD_DB5_LOW			GPIOE->ODR &= ~GPIO_ODR_OD8

#define LCD_DB6_GPIO		GPIOE
#define LCD_DB6_MODER_R	GPIO_MODER_MODER9
#define LCD_DB6_MODER		GPIO_MODER_MODER9_0
#define LCD_DB6_PUPDR		GPIO_PUPDR_PUPDR9_0
#define LCD_DB6_HIGH		GPIOE->ODR |= GPIO_ODR_OD9
#define LCD_DB6_LOW			GPIOE->ODR &= ~GPIO_ODR_OD9

#define LCD_DB7_GPIO		GPIOE
#define LCD_DB7_MODER_R	GPIO_MODER_MODER10
#define LCD_DB7_MODER		GPIO_MODER_MODER10_0
#define LCD_DB7_PUPDR		GPIO_PUPDR_PUPDR10_0
#define LCD_DB7_HIGH		GPIOE->ODR |= GPIO_ODR_OD10
#define LCD_DB7_LOW			GPIOE->ODR &= ~GPIO_ODR_OD10

#define LCD_BKL_GPIO		GPIOB
#define LCD_BKL_MODER_R	GPIO_MODER_MODER13
#define LCD_BKL_MODER		GPIO_MODER_MODER13_0
#define LCD_BKL_PUPDR		GPIO_PUPDR_PUPDR13_0
#define LCD_BKL_HIGH		GPIOB->ODR |= GPIO_ODR_OD13
#define LCD_BKL_LOW			GPIOB->ODR &= ~GPIO_ODR_OD13


#define HD44780_CLEAR							0x01
#define HD44780_HOME							0x02

#define HD44780_ENTRY_MODE				0x04
#define HD44780_EM_SHIFT_CURSOR		0
#define HD44780_EM_SHIFT_DISPLAY	1
#define HD44780_EM_DECREMENT			0
#define HD44780_EM_INCREMENT			2

#define HD44780_DISPLAY_ONOFF			0x08
#define HD44780_DISPLAY_OFF				0
#define HD44780_DISPLAY_ON				4
#define HD44780_CURSOR_OFF				0
#define HD44780_CURSOR_ON					2
#define HD44780_CURSOR_NOBLINK		0
#define HD44780_CURSOR_BLINK			1

#define HD44780_DISPLAY_CURSOR_SHIFT	0x10
#define HD44780_SHIFT_CURSOR			0
#define HD44780_SHIFT_DISPLAY			8
#define HD44780_SHIFT_LEFT				0
#define HD44780_SHIFT_RIGHT				4

#define HD44780_FUNCTION_SET			0x20
#define HD44780_FONT5x7					0
#define HD44780_FONT5x10				4
#define HD44780_ONE_LINE				0
#define HD44780_TWO_LINE				8
#define HD44780_4_BIT					0
#define HD44780_8_BIT					16

#define HD44780_CGRAM_SET				0x40
#define HD44780_DDRAM_SET				0x80

void LCD_WriteText(char *);
void LCD_GoTo(uint8_t, uint8_t);
void LCD_Clear(void);
void LCD_Home(void);
void LCD_Init(void);
void LCD_WriteNumber(int value);

#endif
